[package]
name = "cddl"
description = "Parser for the Concise data definition language (CDDL)"
repository = "https://github.com/anweiss/cddl"
homepage = "https://cddl.anweiss.tech"
categories = ["parser-implementations", "encoding", "development-tools", "wasm"]
license = "MIT"
version = "0.8.3"
authors = ["Andrew Weiss <andrew.weiss@outlook.com>"]
readme = "README.md"
edition = "2018"
exclude = ["cddl-lsp/**/*", "www/**/*", ".github/**/*", ".devcontainer/**/*", "pkg/**/*", ".dockerignore", "Dockerfile", "tests/**/*"]

# Temporary workaround for https://github.com/rustwasm/wasm-pack/issues/886
[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Oz", "--enable-mutable-globals"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base16 = { version = "0.2", default-features = false }
base64 = { version = "0.13", default-features = false }
chrono = { version = "0.4", optional = true }
clap = { version = "2.33", optional = true }
codespan-reporting = "0.9"
itertools = "0.9"
lexical-core = "0.7"
regex = { version = "1.4", default-features = false, features = ["std"] }
regex-syntax = { version = "0.6", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_cbor = { version = "0.11.1", optional = true, default-features = false, features = ["std", "tags"] }
serde_json = { version = "1.0", optional = true, default-features = false }
uriparse = { version = "0.6", optional = true }
base64-url = { version = "1.4", optional = true }

[dev-dependencies]
indoc = "1.0"
pretty_assertions = { git = "https://github.com/colin-kiegel/rust-pretty-assertions" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossterm = { version = "0.18", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
wee_alloc = { version = "0.4", optional = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["std"]
std = ["serde_json", "serde_cbor", "serde", "chrono", "wasm-bindgen", "clap", "crossterm", "uriparse", "base64-url", "regex-syntax"]
lsp = ["std"]

[[bin]]
name = "cli"
required-features = ["std"]
path = "src/bin/cli.rs"
test = false

[[bin]]
name = "repl"
required-features = ["std"]
path = "src/bin/repl.rs"
test = false

[[test]]
name = "cddl"
required-features = ["std"]
path = "tests/cddl.rs"

[profile.release]
opt-level = "s"
lto = true

[badges]
maintenance = { status = "actively-developed" }
