[package]
name = "cddl"
description = "Parser for the Concise data definition language (CDDL)"
repository = "https://github.com/anweiss/cddl"
homepage = "https://cddl.anweiss.tech"
categories = ["parser-implementations", "encoding", "development-tools", "wasm"]
license = "MIT"
version = "0.8.7"
authors = ["Andrew Weiss <andrew.weiss@outlook.com>"]
readme = "README.md"
edition = "2018"
exclude = ["cddl-lsp/**/*", "www/**/*", ".github/**/*", ".devcontainer/**/*", "pkg/**/*", ".dockerignore", "Dockerfile", "tests/**/*"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base16 = { version = "0.2.1", default-features = false }
base64 = { version = "0.13.0", default-features = false }
chrono = { version = "0.4.19", optional = true }
clap = { version = "2.33.3", optional = true }
codespan-reporting = "0.11.1"
hexf-parse = "0.2.1"
itertools = "0.10.1"
lexical-core = "0.7.6"
regex = { version = "1.5.4", default-features = false, features = ["std"] }
regex-syntax = { version = "0.6.25", optional = true }
serde = { version = "1.0.127", optional = true, features = ["derive"] }
serde_cbor = { version = "0.11.1", optional = true, default-features = false, features = ["std", "tags"] }
serde_json = { version = "1.0.66", optional = true, default-features = false }
uriparse = { version = "0.6.3", optional = true }
base64-url = { version = "1.4.10", optional = true }
abnf_to_pest = "0.5"
pest_meta = "2.1"
pest_vm = "2.1"
displaydoc = { version = "0.2.3", default-features = false }

[dev-dependencies]
indoc = "1.0.3"
pretty_assertions = "0.7.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossterm = { version = "0.21.0", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1.6"
wasm-bindgen = { version = "0.2.75", features = ["serde-serialize"], optional = true }
wee_alloc = { version = "0.4.5", optional = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3.25"

[features]
default = ["std", "ast-span", "ast-comments", "json", "cbor"]
std = ["base16/alloc", "base64/alloc", "serde_json", "serde_cbor", "serde", "chrono", "wasm-bindgen", "clap", "crossterm", "uriparse", "base64-url", "regex-syntax"]
lsp = ["std"]
additional-controls = []
ast-span = []
ast-comments = []
json = []
cbor = []

[[bin]]
name = "cddl"
required-features = ["std", "json", "cbor"]
path = "src/bin/cli.rs"
test = false

[[bin]]
name = "repl"
required-features = ["std"]
path = "src/bin/repl.rs"
test = false

[[test]]
name = "cddl"
required-features = ["std", "ast-span", "ast-comments", "json", "cbor"]
path = "tests/cddl.rs"

[profile.release]
opt-level = "s"
lto = true

[badges]
maintenance = { status = "actively-developed" }
