name: Draft release
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/workflows/release-vscode-extension.yml'
      - 'cddl-lsp/**'

jobs:
  compilation-check:
    name: Build and test binaries
    strategy:
      matrix:
        rust_toolchain: [stable]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust_toolchain }}
          override: true

      - name: Check compilation with default features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests

      - name: Check compilation with no features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --examples --tests --no-default-features

      - name: cargo +${{ matrix.rust_toolchain }} test ${{ matrix.os }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

  cargo-publish-dry-run:
    name: Cargo publish dry run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cargo publish --dry-run
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run

  wasm-compilation-check:
    name: Compilation check for wasm target and npm publishing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Install wasmpack
        run: |
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build wasm default features
        run: |
          wasm-pack build --target nodejs --scope anweiss --release

      - name: Build wasm lsp feature
        run: |
          wasm-pack build --target nodejs --scope anweiss --release --out-dir cddl-languageserver -- --features lsp
          sed -i -e 's/"name": "@anweiss\/cddl"/"name": "@anweiss\/cddl-languageserver"/g' cddl-languageserver/package.json

      - name: npm publish dry run
        run: |
          cd pkg
          npm publish --access=public --dry-run
          cd ../cddl-languageserver
          npm publish --access=public --dry-run

  draft-release:
    name: Draft Release
    needs: [compilation-check, cargo-publish-dry-run, wasm-compilation-check]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Draft Release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
